Use correct node version in clean build (#2168)
The clean build was using whatever node version was in the environment.
This updates the `check-build` action to use the `setup-node` action, so
that it uses the expected node version.

A version check is added to the build script. On CI, this aborts the
build. Not on CI, this issues a warning.

The clean build reproducibility checks are also re-enabled. The
reproducibility issues were caused by differences in the compressed
assets. It looks like node statically links zlib, and it looks like the
zlib version from the GHA environment's node differs from the one in our
docker setup (set through `.node-version`).

diff --git a/scripts/build b/scripts/build
--- a/scripts/build
+++ b/scripts/build
@@ -95,6 +95,22 @@ then
     exit 1
 fi
 
+# Check for exact node version
+if [[ "$(node --version)" !=  "v$(cat .node-version)" ]]
+then
+    echo; echo
+    echo "!!!WARNING!!!: could not find node with exact expected version: v$(cat .node-version)"
+    # On CI we abort
+    if [ -n "${CI:-}" ]
+    then
+        exit 1
+    fi
+    # If the node version doesn't match 100% the build might still succeed though is less likely
+    # to be reproducible. For developer convenience we still try to go through.
+    echo "This might cause build or reproducibility issues."
+    echo; echo
+fi
+
 # Builds a single canister
 # build_canister CANISTER EXTRA_BUILD_ARGS...
 # CANISTER: possible values: [internet_identity, archive]
