Document code

diff --git a/scripts/release b/scripts/release
--- a/scripts/release
+++ b/scripts/release
@@ -4,53 +4,71 @@ set -euo pipefail
 declare -a filenames=( )
 declare tag_name
 
+#########
+# USAGE #
+#########
+
 function title() {
     echo "Release Internet Identity"
 }
 
 function usage() {
     cat << EOF
+
 Usage:
   release --tag TAG [-- FILE...]
 
 Options:
   --tag TAG     specify the tag to release
+
 EOF
 }
 
 function help() {
     cat << EOF
 
-
 Any files specified after '--' will be uploaded as release assets.
 
 NOTE: This does not generate release notes. A link will be displayed when the
 release is created. Visit that link to write release notes and click "Auto-generate release notes"
 to add contributions and commit information.
+
 EOF
 
 }
 
+# Check that the command "$1" is installed
 function need_cmd() {
     if ! command -v "$1" >/dev/null
     then
         echo "please install $1"
+        exit 1
     fi
 }
 
-# GitHub Helpers
+##################
+# GITHUB HELPERS #
+##################
+
+# See also
 # https://docs.github.com/en/rest/reference/releases#list-releases
 
+# Ensure that GITHUB_TOKEN is set
 # token needs repo/public_repo scope
 function check_token() {
     if [ -z "${GITHUB_TOKEN:-}" ]
     then
+        echo "Please set GITHUB_TOKEN"
         echo "https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token"
         exit 1
     fi
 }
 
+# Basic curl wrapper to perform a GitHub request.
 function gh() {
+
+    # The request path, can be absolute (https://...) or relative
+    # (in which case it will be prepended with https://api.github.com)
     local path=$1
     shift
     if [[ $path != https://* ]]
@@ -58,9 +76,16 @@ function gh() {
         path="https://api.github.com/${path#"/"}"
     fi
 
+    # Here we want to fail the script if the request is not successful.
+    # Regular curl can do this with --fail; unfortunately when doing so
+    # the body isn't returned, which makes debugging really complicated.
+    # Recent curls have '--fail-with-body', but it isn't available on
+    # GitHub Actions at the time of writing. March 2022
+    #
+    # Instead we write the body to a file and the status code to stdout,
+    # and check that the status code is 2XX.
     local output; output=$(mktemp)
     local http_code
-    # NOTE: cannot use `--fail-with-body` because it's not available on GHA
     http_code=$(curl -w '%{http_code}' -o "$output" --silent  \
             --header "accept: application/vnd.github.v3+json" \
             --header "authorization: token $GITHUB_TOKEN" \
@@ -79,6 +104,7 @@ function gh() {
     fi
 }
 
+# Curl wrapper for sending a JSON document (read from stdin)
 function gh_post_json() {
     local path="$1"
     shift
@@ -87,6 +113,7 @@ function gh_post_json() {
         "$@"
 }
 
+# Curl wrapper for sending a gzipped file (read from stdin)
 function gh_post_tgz() {
     local path="$1"
     local filename="$2"
@@ -96,8 +123,13 @@ function gh_post_tgz() {
         "$@"
 }
 
-# Actual release function
+###########
+# RELEASE #
+###########
 
+# This performs the release by first _creating_ a release (using the value from --tag).
+# The response returned by GitHub includes "upload_url", which is a URL where assets
+# can be POSTed.
 function do_release() {
     local release_json
     release_json=$(jq -n --arg tag_name "$tag_name" '{ tag_name: $tag_name }' \
