Speed up and improve canister tests
This includes a couple of fixes that clarify the canister tests (in
particular end-to-end tests) and that shorten CI runs in most cases
(both for frontend & backend development). A typical CI run should now
be ~5mn shorter (7mn now vs 12mn before):

* The 'selenium' tests are renamed to 'e2e' (since selenium isn't being
  used anymore)
* A new native build job, `cached-build:`, is added and used by the
  canister & e2e tests in lieu of the slower docker builds. The docker
  builds are still used to check the output of the native cached build.
* Some npm packages are removed/deduplicated
* Some `npm ci` steps are run in the background
* The `npm test` step is removed, since unit tests are currently run as
  part of the sharded e2e tests
* A new shard is added to the e2e tests to balance the recently added
  slow verifiable credential tests
* Rustup executables are eagerly loaded (mostly to clarify timings)

diff --git a/.github/workflows/canister-tests.yml b/.github/workflows/canister-tests.yml
--- a/.github/workflows/canister-tests.yml
+++ b/.github/workflows/canister-tests.yml
@@ -1,5 +1,5 @@
 # This describes all the tests we run on the canister code (various builds,
-# integration tests, selenium tests). The canister code is built in docker and the
+# integration tests, e2e tests). The canister code is built in docker and the
 # wasm is then reused by subsequent build steps. We build various flavors of
 # the code, see `docker-build-...` for more info.
 name: Canister tests
@@ -49,7 +49,7 @@ jobs:
           # See job: docker-build-internet_identity_production
 
           # No captcha and fetching the root key, used in (our) tests, backend and
-          # selenium.
+          # e2e.
           - name: internet_identity_test.wasm.gz
             II_FETCH_ROOT_KEY: 1
             II_DUMMY_CAPTCHA: 1
@@ -404,7 +404,7 @@ jobs:
 
   canister-tests-run:
     runs-on: ${{ matrix.os }}
-    needs: [canister-tests-build, docker-build-ii, docker-build-archive]
+    needs: [canister-tests-build, cached-build, docker-build-archive]
     strategy:
       matrix:
         os: [ ubuntu-latest, macos-latest ]
@@ -436,7 +436,7 @@ jobs:
       - name: 'Download II wasm'
         uses: actions/download-artifact@v4
         with:
-          name: internet_identity_test.wasm.gz
+          name: internet_identity_test_cached.wasm.gz
           path: .
 
       - name: 'Download archive wasm'
@@ -462,12 +462,12 @@ jobs:
           RUST_BACKTRACE: 1
 
   ######################
-  # The selenium tests #
+  # The end-to-end tests #
   ######################
 
-  selenium:
+  e2e:
     runs-on: ubuntu-latest
-    needs: [docker-build-ii, test-app-build, vc_demo_issuer-build]
+    needs: [cached-build, test-app-build, vc_demo_issuer-build]
     strategy:
       matrix:
         device: [ 'desktop', 'mobile' ]
@@ -478,7 +478,7 @@ jobs:
         # based on the shard assigned to it)
         # The jest parameter is actually 1/N, 2/N etc but we use a artifact-friendly
         # version here (with underscore).
-        shard: [ '1_5', '2_5', '3_5', '4_5', '5_5' ]
+        shard: [ '1_6', '2_6', '3_6', '4_6', '5_6', '6_6' ]
       # Make sure that one failing test does not cancel all other matrix jobs
       fail-fast: false
 
@@ -490,6 +490,11 @@ jobs:
       - uses: actions/checkout@v3
       - uses: ./.github/actions/setup-node
 
+      # npm ci is a slow operation that mostly involves downloading packages, so we run
+      # it in the background while we set up the replica
+      - name: Kickstart npm ci
+        run: '{ npm ci --no-audit --no-fund; echo "$?" > ~/npm-ci-status; } &'
+
       - uses: ./.github/actions/setup-dfx
 
       # Helps with debugging
@@ -500,17 +505,13 @@ jobs:
           echo node --version
           node --version
 
-      # Setup npm and run fast tests early
-      - run: npm ci
-      - run: npm test
-
       - name: 'Run dfx'
         run: dfx start --background --artificial-delay 0
 
       - name: 'Download II wasm'
         uses: actions/download-artifact@v4
         with:
-          name: internet_identity_test.wasm.gz
+          name: internet_identity_test_cached.wasm.gz
           path: .
 
       - name: 'Download test app wasm'
@@ -537,6 +538,14 @@ jobs:
       - name: Provision issuer canister
         run: ./demos/vc_issuer/provision
 
+      # Check the return code of npm ci
+      - name: Check on npm ci
+        # make sure we don't wait too long if for some unlikely reason the npm status file doesn't get created
+        timeout-minutes: 1
+        run: |
+          until [ -f ~/npm-ci-status ]; do sleep 1; done
+          exit $(cat ~/npm-ci-status)
+
       - name: Run dev server
         id: dev-server-start
         run: |
@@ -544,6 +553,7 @@ jobs:
           dev_server_pid=$!
           echo "dev_server_pid=$dev_server_pid" >> "$GITHUB_OUTPUT"
 
+      # run unit tests & e2e tests
       # NOTE: we run chrome in headless mode because that's the only thing that works in GHA
       # NOTE: the last bit (tr) replaces 1_N with 1/N
       - run: |
@@ -576,12 +586,12 @@ jobs:
           path: test-failures/*
           if-no-files-found: ignore
 
-  # Aggregate all selenium matrix jobs, used in branch protection
-  selenium-all:
+  # Aggregate all e2e matrix jobs, used in branch protection
+  e2e-all:
     runs-on: ubuntu-latest
-    needs: selenium
+    needs: e2e
     steps:
-      - run: echo selenium ok
+      - run: echo e2e ok
 
   using-dev-build:
     runs-on: ubuntu-latest
@@ -840,6 +850,76 @@ jobs:
           # populated by GitHub Actions
           # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+  # A native, fast cached build. We use the produced test assets to run the canister & e2e tests.
+  # The asset's checksum is compared against that of the (slower) docker build.
+  cached-build:
+    runs-on: ubuntu-22.04
+    steps:
+      - uses: actions/checkout@v3
+      - uses: actions/cache@v3
+        id: cache
+        with:
+          path: |
+            ~/.cargo
+            target
+          key: ${{ runner.os }}-cached-build-${{ hashFiles('rust-toolchain.toml', 'Cargo.lock', '.node-version', 'package-lock.json') }}
+
+      - uses: ./.github/actions/bootstrap
+      - uses: ./.github/actions/setup-node
+
+      # run the build
+      # NOTE: npm ci is only ~2s slower than an offline install (npm i --offline), so we use npm ci to have
+      # a Clean Install
+      - run: npm ci --no-audit --no-fund
+
+      - name: Build test flavor
+        env:
+          II_FETCH_ROOT_KEY: 1
+          II_DUMMY_CAPTCHA: 1
+          II_DUMMY_AUTH: 0
+          II_INSECURE_REQUESTS: 0
+        run: ./scripts/build
+
+      - run: mv internet_identity.wasm.gz internet_identity_test.wasm.gz
+      - name: 'Upload test build'
+        uses: actions/upload-artifact@v4
+        with:
+          # name is the name used to display and retrieve the artifact
+          name: internet_identity_test_cached.wasm.gz
+          # path is the name used as the file to upload and the name of the
+          # file when downloaded
+          path: internet_identity_test.wasm.gz
+
+  # Make sure that the asset we're testing is the same as that produced by the (slower) docker builds
+  cached-build-check:
+    runs-on: ubuntu-22.04
+    needs: [docker-build-ii, cached-build]
+    steps:
+      - uses: actions/checkout@v3
+      - name: 'Download docker build'
+        uses: actions/download-artifact@v4
+        with:
+          name: internet_identity_test.wasm.gz
+          path: .
+      - run: mv internet_identity_test.wasm.gz docker.wasm.gz
+      - name: 'Download native cached build'
+        uses: actions/download-artifact@v4
+        with:
+          name: internet_identity_test_cached.wasm.gz
+          path: .
+      - run: mv internet_identity_test.wasm.gz native.wasm.gz
+      - run: |
+          native_sha256=$(shasum -a 256 ./native.wasm.gz | cut -d ' ' -f1)
+          docker_sha256=$(shasum -a 256 ./docker.wasm.gz | cut -d ' ' -f1)
+          echo "shas: native '$native_sha256', docker '$docker_sha256'"
+          if [ "$native_sha256" == "$docker_sha256" ]
+          then
+            echo output sha256 matches expected
+          else
+            echo "sha mismatch"
+            exit 1
+          fi
 
   clean-build:
     runs-on: ${{ matrix.os }}
