Implement e2e tests for new authorize flow with playwright.

diff --git a/.github/workflows/canister-tests.yml b/.github/workflows/canister-tests.yml
--- a/.github/workflows/canister-tests.yml
+++ b/.github/workflows/canister-tests.yml
@@ -524,7 +524,7 @@ jobs:
           # (i.e. capitalize the first letter)
           captcha_variant="Captcha$(tr '[:lower:]' '[:upper:]' <<< ${captcha_flag:0:1})${captcha_flag:1}"
           # NOTE: dfx install will run the postinstall scripts from dfx.json
-          dfx canister install internet_identity --wasm internet_identity_test.wasm.gz --argument "(opt record { captcha_config = opt record { max_unsolved_captchas= 50:nat64; captcha_trigger = variant {Static = variant { $captcha_variant }}}; related_origins = opt vec { \"https://identity.internetcomputer.org\"; \"https://identity.ic0.app\" }; dummy_auth = opt opt record { prompt_for_index = true }})"
+          dfx canister install internet_identity --wasm internet_identity_test.wasm.gz --argument "(opt record { captcha_config = opt record { max_unsolved_captchas= 50:nat64; captcha_trigger = variant {Static = variant { $captcha_variant }}}; related_origins = opt vec { \"https://identity.internetcomputer.org\"; \"https://identity.ic0.app\" }})"
           dfx canister install test_app --wasm demos/test-app/test_app.wasm
           dfx canister install issuer --wasm demos/vc_issuer/vc_demo_issuer.wasm.gz
 
@@ -576,11 +576,110 @@ jobs:
           name: e2e-test-failures-${{ env.artifact_suffix }}
           path: test-failures/*
           if-no-files-found: ignore
+  
+  e2e-playwright:
+    runs-on: ubuntu-latest
+    needs: [ cached-build, test-app-build ]
+    strategy:
+      matrix:
+        device: [ "desktop", "mobile" ]
+        shard: [ "1_6", "2_6", "3_6", "4_6", "5_6", "6_6" ]
+      # Make sure that one failing test does not cancel all other matrix jobs
+      fail-fast: false
+
+    env:
+      # Suffix used for tagging artifacts
+      artifact_suffix: next-${{ matrix.device }}-${{ matrix.shard }}
+
+    steps:
+      - uses: actions/checkout@v4
+      - uses: ./.github/actions/setup-node
+
+      # npm ci is a slow operation that mostly involves downloading packages, so we run
+      # it in the background while we set up the replica
+      - name: Kickstart npm ci
+        run: '{ npm ci --no-audit --no-fund; echo "$?" > ~/npm-ci-status; } &'
+
+      - uses: dfinity/setup-dfx@e50c04f104ee4285ec010f10609483cf41e4d365
+
+      # Helps with debugging
+      - name: Show versions
+        run: |
+          echo dfx --version
+          dfx --version
+          echo node --version
+          node --version
+
+      - name: "Run dfx"
+        run: dfx start --background --artificial-delay 0
+
+      - name: "Download II wasm"
+        uses: actions/download-artifact@v4
+        with:
+          name: internet_identity_test_cached.wasm.gz
+          path: .
+
+      - name: "Download test app wasm"
+        uses: actions/download-artifact@v4
+        with:
+          name: test_app.wasm
+          path: demos/test-app
+
+      - name: Create Canisters
+        run: dfx canister create --all
+
+      - name: Deploy canisters
+        run: |
+          # NOTE: dfx install will run the postinstall scripts from dfx.json
+          dfx canister install internet_identity --wasm internet_identity_test.wasm.gz --argument "(opt record { captcha_config = opt record { max_unsolved_captchas= 50:nat64; captcha_trigger = variant {Static = variant { CaptchaDisabled }}}; related_origins = opt vec { \"https://id.ai\" }; new_flow_origins = opt vec { \"https://id.ai\" }; dummy_auth = opt opt record { prompt_for_index = true }})"
+          dfx canister install test_app --wasm demos/test-app/test_app.wasm
+
+      # Check the return code of npm ci
+      - name: Check on npm ci
+        # make sure we don't wait too long if for some unlikely reason the npm status file doesn't get created
+        timeout-minutes: 5
+        run: |
+          until [ -f ~/npm-ci-status ]; do sleep 1; done
+          exit $(cat ~/npm-ci-status)
+
+      - name: Run dev server
+        id: dev-server-start
+        run: |
+          TLS_DEV_SERVER=1 NO_HOT_RELOAD=1 npm run dev | tee -a > dev-server-logs.txt &
+          dev_server_pid=$!
+          echo "dev_server_pid=$dev_server_pid" >> "$GITHUB_OUTPUT"
+
+      - run: |
+          npx playwright test --project ${{ matrix.device }} --workers 3 --shard=$(tr <<<'${{ matrix.shard }}' -s _ /)
+
+      - name: Stop dfx
+        if: ${{ always() }}
+        run: dfx stop
+
+      - name: Stop dev server
+        if: ${{ always() }}
+        run: kill ${{ steps.dev-server-start.outputs.dev_server_pid }}
+
+      - name: Archive dev server logs
+        if: ${{ always() }}
+        uses: actions/upload-artifact@v4
+        with:
+          name: dev-server-logs-${{ env.artifact_suffix }}
+          path: dev-server-logs.txt
+          if-no-files-found: ignore
+
+      - name: Archive test failures
+        if: ${{ always() }}
+        uses: actions/upload-artifact@v4
+        with:
+          name: e2e-test-failures-${{ env.artifact_suffix }}
+          path: test-failures/*
+          if-no-files-found: ignore
 
   # Aggregate all e2e matrix jobs, used in branch protection
   e2e-all:
     runs-on: ubuntu-latest
-    needs: e2e
+    needs: [ e2e, e2e-playwright ]
     steps:
       - run: echo e2e ok
 
