wip

diff --git a/.github/workflows/canister-tests.yml b/.github/workflows/canister-tests.yml
--- a/.github/workflows/canister-tests.yml
+++ b/.github/workflows/canister-tests.yml
@@ -15,6 +15,7 @@ jobs:
 
   # The image shared by all builds, containing pre-built rust deps
   docker-build-base:
+    if: false
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
@@ -36,6 +37,7 @@ jobs:
           target: deps
 
   docker-build:
+    if: false
     runs-on: ubuntu-latest
     needs: docker-build-base
     strategy:
@@ -100,6 +102,7 @@ jobs:
   #####################
 
   backend:
+    if: false
     runs-on: ${{ matrix.os }}
     needs: docker-build
     strategy:
@@ -149,6 +152,7 @@ jobs:
   ######################
 
   selenium:
+    if: false
     runs-on: ubuntu-latest
     needs: docker-build
     strategy:
@@ -253,6 +257,7 @@ jobs:
           path: screenshots/**/*.png
 
   using-dev-build:
+    if: false
     runs-on: ubuntu-latest
     needs: docker-build
     env:
@@ -332,18 +337,22 @@ jobs:
     if: ${{ github.ref != 'refs/heads/main' }}
     steps:
       - uses: actions/checkout@v2
+        if: false
 
       # Make sure old screenshots don't pollute the commit
       - run: rm -v -f screenshots/*.png
+        if: false
 
       # Download the desktop screenshots artifacts
       - uses: actions/download-artifact@v2
+        if: false
         with:
           name: e2e-screenshots-desktop
           path: screenshots
 
       # Download the mobile screenshots artifacts
       - uses: actions/download-artifact@v2
+        if: false
         with:
           name: e2e-screenshots-mobile
           path: screenshots
@@ -351,6 +360,43 @@ jobs:
       - run: |
           echo "The following screenshots were recovered:"
           shasum -a 256 screenshots/*.png | sort -k2 # sort by 2nd column (filename)
+        if: false
+
+      - run: |
+          cp dummy.png screenshots/19-after-removal-mobile.png
+          sudo apt install imagemagick
+          for modified in $(git ls-files --modified ./screenshots)
+          do
+            echo found modified screenshot "$modified"
+            old=$(mktemp)
+            git show HEAD:$modified > $out
+            magick_out=$(mktemp)
+            if ! magick compare -metric AE "$modified" "$old" /dev/null 2> "$magick_out"
+            then
+              echo "Magick failed"
+              rm "$old"
+              cat "$magick_out"
+              rm "$magick_out"
+              exit 1
+            fi
+
+            rm "$old"
+
+            metric=$(<"$magick_out"); rm "$magick_out"
+            if ! [[ $metric =~ ^[0-9]+$ ]]
+            then
+              echo "magick didn't return a number"
+              exit 1
+            fi
+
+            echo "Magick says $metric pixels differ"
+
+            if (( metric <= 8 ))
+            then
+              echo "That's too small; reverting"
+              git checkout HEAD -- "$modified"
+            fi
+          done
 
       - name: Commit screenshots
         uses: EndBug/add-and-commit@v9
